### ISSUE TITLE
Add name validation for Python code

### ISSUE THREAD

**Issue by dmodena** [dmodena/polyglot-registration#13]
The Python console app needs to validate the input name. Please follow validation rules from [documentation](https://github.com/dmodena/polyglot-registration/blob/main/src/README.md).

**Comment by HyperTHD** [comment]
I'd like to take this issue on if you don't mind

**Comment by dmodena** [comment]
Please, go ahead and submit your pull request!

**Comment by dmodena** [comment]
Closed on PR #24 . @HyperTHD  if you still want to work on it, feel free to submit a PR, and I will mark it as good to count for Hacktoberfest.

**Comment by HyperTHD** [comment]
@dmodena Thanks, I'm kinda sad it got taken although I got assigned, but it's all good. I'm gonna push my PR now

**Comment by dmodena** [comment]
Thank you for your contribution, @HyperTHD ! The issue was open for anyone to submit PR for Hacktoberfest. I reviewed your PR, it looks good! I marked it as accepted for Hacktoberfest.

**Comment by dmodena** [comment]
@all-contributors please add HyperTHD for code.
