### ISSUE TITLE
Add document validation for Python code

### ISSUE THREAD

**Issue by dmodena** [dmodena/polyglot-registration#14]
The Python console app needs to validate the input document. Please follow validation rules from [documentation](https://github.com/dmodena/polyglot-registration/blob/main/src/README.md).

**Comment by lcpizzo** [comment]
Hi, I'd like to try!

**Comment by lcpizzo** [comment]
Hi, I'd like to try!

**Comment by dmodena** [comment]
Please go ahead, and submit your pull request!

**Comment by dmodena** [comment]
Closed on PR #26
