### ISSUE TITLE
Add email validation for Python code

### ISSUE THREAD

**Issue by dmodena** [dmodena/polyglot-registration#15]
The Python console app needs to validate the input email. Please follow validation rules from [documentation](https://github.com/dmodena/polyglot-registration/blob/main/src/README.md).

**Comment by yuanLeeMidori** [comment]
Hi! Has there been any developer working on this issue? I just learned Python and would like to give it a try. Thank you!

**Comment by dmodena** [comment]
Great! Please, go ahead and submit your pull request!

**Comment by pk-95** [comment]
Hey, I would like to give this issue a go!

**Comment by dmodena** [comment]
Please, go ahead and submit a pull request! I will be taking the first PR to pass the tests.

**Comment by phoffmeister** [comment]
Hey I hope its fine that I submitted a PR for this one.

**Comment by dmodena** [comment]
Closed on PR #20

**Comment by dmodena** [comment]
@yuanLeeMidori @pk-95 If you are still working on this issue, feel free to submit a pull request, and I will mark it as accepted, to count towards Hacktoberfest.

**Comment by yuanLeeMidori** [comment]
@dmodena Thank you! I started to work on the name validator instead while I saw the email validator has been closed by other PR.
