### ISSUE TITLE
Add document validation for C# code

### ISSUE THREAD

**Issue by dmodena** [dmodena/polyglot-registration#5]
The C# console app needs to validate the input document. Please follow validation rules from [documentation](https://github.com/dmodena/polyglot-registration/blob/main/src/README.md).

**Comment by gitrahulgit** [comment]
I want to work on it

**Comment by dmodena** [comment]
@gitrahulgit feel free to submit one Pull Request. Please notice that during this month, only one PR by contributor will be accepted.

**Comment by dmodena** [comment]
Closed on PR #34
