### ISSUE TITLE
Add document validation for Ruby code

### ISSUE THREAD

**Issue by dmodena** [dmodena/polyglot-registration#8]
The Ruby console app needs to validate the input document. Please follow validation rules from [documentation](https://github.com/dmodena/polyglot-registration/blob/main/src/README.md).

**Comment by sharkham** [comment]
Can I take this one?

**Comment by dmodena** [comment]
Please go ahead and submit your PR!

**Comment by sharkham** [comment]
Thanks @dmodena ! PR has been submitted. It failed the tests, but as far as I can tell that's because the test for email validation failed--which wasn't the thing I was working on, so I think it's fine.

**Comment by dmodena** [comment]
PR closed on #37
