### ISSUE TITLE
Add email validation for Ruby code

### ISSUE THREAD

**Issue by dmodena** [dmodena/polyglot-registration#9]
The Ruby console app needs to validate the input email. Please follow validation rules from [documentation](https://github.com/dmodena/polyglot-registration/blob/main/src/README.md).

**Comment by gitrahulgit** [comment]
I would like to work on it!!

**Comment by dmodena** [comment]
Please go ahead and submit your PR

**Comment by dmodena** [comment]
Closed with [4f3e227](https://github.com/dmodena/polyglot-registration/commit/4f3e227c571e801e8794111488bfcf0e84a1f059).
